# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: buildSolution
        displayName: Build & Test Solution
        pool:
          name: emeni-build-windows
        steps:
          - task: UseDotNet@2
            displayName: Use .NET 10
            inputs:
              packageType: 'sdk'
              version: '10.x'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Build solution
            inputs:
              command: 'build'
              projects: 'DutchMetar.slnx'
              arguments: '-c Release'

          - task: DotNetCoreCLI@2
            displayName: Run solution tests
            inputs:
              command: 'test'
              projects: 'DutchMetar.slnx'
              testRunTitle: '.NET Tests'

      - job: publishHangfireImage
        displayName: Publish DutchMetar Hangfire image
        dependsOn: buildSolution
        variables:
        - group: GithubPackages

        steps: 
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $xmlContent = @"
                <?xml version="1.0" encoding="utf-8"?>
                <configuration>
                  <packageSources>
                    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
                    <add key="github" value="https://nuget.pkg.github.com/Okan1701/index.json" />
                  </packageSources>
                  <packageSourceCredentials>
                    <github>
                        <add key="Username" value="$(UserName)" />
                        <add key="ClearTextPassword" value="$(ApiKey)" />
                    </github>
                  </packageSourceCredentials>
                </configuration>
                "@
                
                Set-Content -Path "./src/DutchMetar.Hangfire.Host/nuget.config" -Value $xmlContent -Encoding UTF8
          - task: Docker@2
            displayName: Build & Push
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'ultimateantic/dutchmetar-jobs'
              command: 'buildAndPush'
              Dockerfile: 'src/DutchMetar.Hangfire.Host/Dockerfile'
              buildContext: '.'
              tags: 'latest'