# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: buildSolution
        displayName: Build & Test Solution
        steps:
          - task: UseDotNet@2
            displayName: Use .NET 10
            inputs:
              packageType: 'sdk'
              version: '10.x'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Build solution
            inputs:
              command: 'build'
              projects: 'DutchMetar.slnx'
              arguments: '-c Release'

          - task: DotNetCoreCLI@2
            displayName: Run solution tests
            inputs:
              command: 'test'
              projects: 'DutchMetar.slnx'
              testRunTitle: '.NET Tests'

      - job: publishHangfireImage
        displayName: Publish DutchMetar Hangfire image
        steps: 
          - task: Docker@2
            inputs:
              containerRegistry: 'Docker Hub'
              repository: 'ultimateantic/dutchmetar-jobs'
              command: 'buildAndPush'
              Dockerfile: 'src/DutchMetar.Hangfire.Host/Dockerfile'
              buildContext: '.'
              tags: 'latest'